#!/bin/sh
# Regenerate wire-protocol bindings from pet/pet.fbs. Outputs are committed so
# a plain `arduino-cli compile` and `./talk.py` never need flatc installed.
#
# The ESP32 toolchain bundles an old flatbuffers (23.5.26, via esp-tflite-micro)
# whose include path shadows any Arduino library. To use the flatc-matching
# runtime we amalgamate its headers into one self-contained file in the sketch
# and point the generated header at it, so "flatbuffers/..." is never included.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
FLATC="${FLATC:-flatc}"
FB_INCLUDE="${FB_INCLUDE:-/opt/homebrew/include}"

# C++ -> sketch src/ (compiled recursively by arduino-cli).
"$FLATC" --cpp --scoped-enums -o "$HERE/pet/src" "$HERE/pet/pet.fbs"

# Amalgamate the flatbuffers C++ runtime (header-only) into the sketch.
python3 - "$FB_INCLUDE" "$HERE/pet/src/flatbuffers_runtime.h" <<'EOF'
import re, sys
root, out = sys.argv[1], sys.argv[2]
seen = set()
def inline(path):
    if path in seen:
        return ""
    seen.add(path)
    lines = []
    for line in open(f"{root}/{path}"):
        m = re.match(r'\s*#include\s+"(flatbuffers/[^"]+)"', line)
        lines.append(inline(m.group(1)) if m else line)
    return "".join(lines)
body = inline("flatbuffers/flatbuffers.h")
with open(out, "w") as f:
    f.write("// Amalgamated flatbuffers C++ runtime — generated by gen.sh, do not edit.\n"
            f"// Source: {root}/flatbuffers/*.h\n")
    f.write(body)
EOF

# Point the generated header at the amalgamated runtime.
sed -i '' 's|#include "flatbuffers/flatbuffers.h"|#include "flatbuffers_runtime.h"|' \
    "$HERE/pet/src/pet_generated.h"

# Python -> single module under petproto/ (imported by talk.py).
"$FLATC" --python --gen-onefile -o "$HERE/petproto" "$HERE/pet/pet.fbs"

echo "generated pet/src/pet_generated.h, pet/src/flatbuffers_runtime.h, petproto/"
