# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Channel(object):
    BOTH = 0
    ONE = 1
    TWO = 2


class NumCmd(object):
    GOTO = 0
    MOVE_BY = 1
    MAX_SPEED = 2
    MAX_PWM = 3
    MIN_PWM = 4
    KP = 5
    KI = 6
    KD = 7
    SET_DIR = 8
    GROUND_SPEED = 9
    AIR_SPEED = 10


class SimpleCmd(object):
    STAND = 0
    ZERO = 1
    STOP = 2
    ENC_HEALTH = 3
    STATUS = 4
    RESET = 5
    HELP = 6


class Toggle(object):
    STATUS_STREAM = 0
    RAW_STREAM = 1


class LogLevel(object):
    INFO = 0
    WARN = 1
    ERROR = 2


class WifiState(object):
    UNCONFIGURED = 0
    CONNECTING = 1
    CONNECTED = 2
    FAILED = 3


class WalkPhase(object):
    START = 0
    LEADIN = 1
    STEPPING = 2
    LEADOUT = 3
    DONE = 4
    ABORTED = 5


class Msg(object):
    NONE = 0
    NumberCmd = 1
    SimpleAction = 2
    Calibrate = 3
    PulseCmd = 4
    ToggleCmd = 5
    WalkCmd = 6
    WifiCmd = 7
    Ack = 8
    Log = 9
    Status = 10
    EncoderHealth = 11
    PulseResult = 12
    WalkEvent = 13
    WifiStatus = 14


class NumberCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NumberCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNumberCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NumberCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # NumberCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NumberCmd
    def Cmd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # NumberCmd
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # NumberCmd
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def NumberCmdStart(builder):
    builder.StartObject(3)

def NumberCmdAddCmd(builder, cmd):
    builder.PrependInt8Slot(0, cmd, 0)

def NumberCmdAddChannel(builder, channel):
    builder.PrependInt8Slot(1, channel, 0)

def NumberCmdAddValue(builder, value):
    builder.PrependFloat32Slot(2, value, 0.0)

def NumberCmdEnd(builder):
    return builder.EndObject()



class SimpleAction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimpleAction()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSimpleAction(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SimpleActionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # SimpleAction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimpleAction
    def Cmd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def SimpleActionStart(builder):
    builder.StartObject(1)

def SimpleActionAddCmd(builder, cmd):
    builder.PrependInt8Slot(0, cmd, 0)

def SimpleActionEnd(builder):
    return builder.EndObject()



class Calibrate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Calibrate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCalibrate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CalibrateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # Calibrate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Calibrate
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def CalibrateStart(builder):
    builder.StartObject(1)

def CalibrateAddChannel(builder, channel):
    builder.PrependInt8Slot(0, channel, 0)

def CalibrateEnd(builder):
    return builder.EndObject()



class PulseCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PulseCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPulseCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PulseCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # PulseCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PulseCmd
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # PulseCmd
    def Pwm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # PulseCmd
    def Ms(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def PulseCmdStart(builder):
    builder.StartObject(3)

def PulseCmdAddChannel(builder, channel):
    builder.PrependInt8Slot(0, channel, 0)

def PulseCmdAddPwm(builder, pwm):
    builder.PrependInt16Slot(1, pwm, 0)

def PulseCmdAddMs(builder, ms):
    builder.PrependInt16Slot(2, ms, 0)

def PulseCmdEnd(builder):
    return builder.EndObject()



class ToggleCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ToggleCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsToggleCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ToggleCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # ToggleCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ToggleCmd
    def Which(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def ToggleCmdStart(builder):
    builder.StartObject(1)

def ToggleCmdAddWhich(builder, which):
    builder.PrependInt8Slot(0, which, 0)

def ToggleCmdEnd(builder):
    return builder.EndObject()



class WalkCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WalkCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWalkCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WalkCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # WalkCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WalkCmd
    def Steps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WalkCmd
    def PhaseDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 180.0

def WalkCmdStart(builder):
    builder.StartObject(2)

def WalkCmdAddSteps(builder, steps):
    builder.PrependInt32Slot(0, steps, 0)

def WalkCmdAddPhaseDeg(builder, phaseDeg):
    builder.PrependFloat32Slot(1, phaseDeg, 180.0)

def WalkCmdEnd(builder):
    return builder.EndObject()



class WifiCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WifiCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWifiCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WifiCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # WifiCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WifiCmd
    def Ssid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WifiCmd
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WifiCmdStart(builder):
    builder.StartObject(2)

def WifiCmdAddSsid(builder, ssid):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ssid), 0)

def WifiCmdAddPassword(builder, password):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)

def WifiCmdEnd(builder):
    return builder.EndObject()



class Ack(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Ack()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AckBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # Ack
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Ack
    def Ok(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # Ack
    def Detail(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AckStart(builder):
    builder.StartObject(2)

def AckAddOk(builder, ok):
    builder.PrependBoolSlot(0, ok, 1)

def AckAddDetail(builder, detail):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(detail), 0)

def AckEnd(builder):
    return builder.EndObject()



class Log(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Log()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLog(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LogBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # Log
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Log
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Log
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LogStart(builder):
    builder.StartObject(2)

def LogAddLevel(builder, level):
    builder.PrependInt8Slot(0, level, 0)

def LogAddText(builder, text):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)

def LogEnd(builder):
    return builder.EndObject()



class ServoState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ServoState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsServoState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ServoStateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # ServoState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ServoState
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ServoState
    def Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServoState
    def Fault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServoState
    def FaultName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ServoState
    def PositionTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ServoState
    def TargetTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ServoState
    def VelocityTps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ServoState
    def Pwm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def ServoStateStart(builder):
    builder.StartObject(8)

def ServoStateAddChannel(builder, channel):
    builder.PrependInt8Slot(0, channel, 0)

def ServoStateAddEnabled(builder, enabled):
    builder.PrependBoolSlot(1, enabled, 0)

def ServoStateAddFault(builder, fault):
    builder.PrependBoolSlot(2, fault, 0)

def ServoStateAddFaultName(builder, faultName):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(faultName), 0)

def ServoStateAddPositionTurns(builder, positionTurns):
    builder.PrependFloat32Slot(4, positionTurns, 0.0)

def ServoStateAddTargetTurns(builder, targetTurns):
    builder.PrependFloat32Slot(5, targetTurns, 0.0)

def ServoStateAddVelocityTps(builder, velocityTps):
    builder.PrependFloat32Slot(6, velocityTps, 0.0)

def ServoStateAddPwm(builder, pwm):
    builder.PrependInt16Slot(7, pwm, 0)

def ServoStateEnd(builder):
    return builder.EndObject()



class Status(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Status()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StatusBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # Status
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Status
    def Servos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ServoState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Status
    def ServosLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Status
    def ServosIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StatusStart(builder):
    builder.StartObject(1)

def StatusAddServos(builder, servos):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(servos), 0)

def StatusStartServosVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StatusEnd(builder):
    return builder.EndObject()



class EncoderInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EncoderInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEncoderInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EncoderInfoBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # EncoderInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EncoderInfo
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # EncoderInfo
    def Connected(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EncoderInfo
    def MagnetDetected(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EncoderInfo
    def MagnetTooWeak(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EncoderInfo
    def MagnetTooStrong(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EncoderInfo
    def Agc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EncoderInfo
    def Magnitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # EncoderInfo
    def AngleDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def EncoderInfoStart(builder):
    builder.StartObject(8)

def EncoderInfoAddChannel(builder, channel):
    builder.PrependInt8Slot(0, channel, 0)

def EncoderInfoAddConnected(builder, connected):
    builder.PrependBoolSlot(1, connected, 0)

def EncoderInfoAddMagnetDetected(builder, magnetDetected):
    builder.PrependBoolSlot(2, magnetDetected, 0)

def EncoderInfoAddMagnetTooWeak(builder, magnetTooWeak):
    builder.PrependBoolSlot(3, magnetTooWeak, 0)

def EncoderInfoAddMagnetTooStrong(builder, magnetTooStrong):
    builder.PrependBoolSlot(4, magnetTooStrong, 0)

def EncoderInfoAddAgc(builder, agc):
    builder.PrependUint8Slot(5, agc, 0)

def EncoderInfoAddMagnitude(builder, magnitude):
    builder.PrependUint16Slot(6, magnitude, 0)

def EncoderInfoAddAngleDeg(builder, angleDeg):
    builder.PrependFloat32Slot(7, angleDeg, 0.0)

def EncoderInfoEnd(builder):
    return builder.EndObject()



class EncoderHealth(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EncoderHealth()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEncoderHealth(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EncoderHealthBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # EncoderHealth
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EncoderHealth
    def Encoders(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = EncoderInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EncoderHealth
    def EncodersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EncoderHealth
    def EncodersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EncoderHealthStart(builder):
    builder.StartObject(1)

def EncoderHealthAddEncoders(builder, encoders):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(encoders), 0)

def EncoderHealthStartEncodersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def EncoderHealthEnd(builder):
    return builder.EndObject()



class PulseResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PulseResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPulseResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PulseResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # PulseResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PulseResult
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # PulseResult
    def Pwm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # PulseResult
    def Ms(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # PulseResult
    def Enc1DeltaCounts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PulseResult
    def Enc1DeltaTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PulseResult
    def Enc2DeltaCounts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PulseResult
    def Enc2DeltaTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PulseResult
    def CrossWired(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PulseResultStart(builder):
    builder.StartObject(8)

def PulseResultAddChannel(builder, channel):
    builder.PrependInt8Slot(0, channel, 0)

def PulseResultAddPwm(builder, pwm):
    builder.PrependInt16Slot(1, pwm, 0)

def PulseResultAddMs(builder, ms):
    builder.PrependInt16Slot(2, ms, 0)

def PulseResultAddEnc1DeltaCounts(builder, enc1DeltaCounts):
    builder.PrependInt64Slot(3, enc1DeltaCounts, 0)

def PulseResultAddEnc1DeltaTurns(builder, enc1DeltaTurns):
    builder.PrependFloat32Slot(4, enc1DeltaTurns, 0.0)

def PulseResultAddEnc2DeltaCounts(builder, enc2DeltaCounts):
    builder.PrependInt64Slot(5, enc2DeltaCounts, 0)

def PulseResultAddEnc2DeltaTurns(builder, enc2DeltaTurns):
    builder.PrependFloat32Slot(6, enc2DeltaTurns, 0.0)

def PulseResultAddCrossWired(builder, crossWired):
    builder.PrependBoolSlot(7, crossWired, 0)

def PulseResultEnd(builder):
    return builder.EndObject()



class WalkEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WalkEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWalkEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WalkEventBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # WalkEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WalkEvent
    def Phase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # WalkEvent
    def Steps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WalkEvent
    def LeadServo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def WalkEventStart(builder):
    builder.StartObject(3)

def WalkEventAddPhase(builder, phase):
    builder.PrependInt8Slot(0, phase, 0)

def WalkEventAddSteps(builder, steps):
    builder.PrependInt32Slot(1, steps, 0)

def WalkEventAddLeadServo(builder, leadServo):
    builder.PrependInt8Slot(2, leadServo, 0)

def WalkEventEnd(builder):
    return builder.EndObject()



class WifiStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WifiStatus()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWifiStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WifiStatusBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # WifiStatus
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WifiStatus
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # WifiStatus
    def Ssid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WifiStatus
    def Ip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WifiStatus
    def Hostname(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WifiStatus
    def Rssi(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # WifiStatus
    def WsClients(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def WifiStatusStart(builder):
    builder.StartObject(6)

def WifiStatusAddState(builder, state):
    builder.PrependInt8Slot(0, state, 0)

def WifiStatusAddSsid(builder, ssid):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ssid), 0)

def WifiStatusAddIp(builder, ip):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ip), 0)

def WifiStatusAddHostname(builder, hostname):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(hostname), 0)

def WifiStatusAddRssi(builder, rssi):
    builder.PrependInt16Slot(4, rssi, 0)

def WifiStatusAddWsClients(builder, wsClients):
    builder.PrependUint8Slot(5, wsClients, 0)

def WifiStatusEnd(builder):
    return builder.EndObject()



class Packet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Packet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPacket(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PacketBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x45\x54\x31", size_prefixed=size_prefixed)

    # Packet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Packet
    def ReqId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Packet
    def MsgType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Packet
    def Msg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def PacketStart(builder):
    builder.StartObject(3)

def PacketAddReqId(builder, reqId):
    builder.PrependUint32Slot(0, reqId, 0)

def PacketAddMsgType(builder, msgType):
    builder.PrependUint8Slot(1, msgType, 0)

def PacketAddMsg(builder, msg):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(msg), 0)

def PacketEnd(builder):
    return builder.EndObject()



