// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PET_PET_WIRE_H_
#define FLATBUFFERS_GENERATED_PET_PET_WIRE_H_

#include "flatbuffers_runtime.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace pet {
namespace wire {

struct NumberCmd;
struct NumberCmdBuilder;

struct SimpleAction;
struct SimpleActionBuilder;

struct Calibrate;
struct CalibrateBuilder;

struct PulseCmd;
struct PulseCmdBuilder;

struct ToggleCmd;
struct ToggleCmdBuilder;

struct WalkCmd;
struct WalkCmdBuilder;

struct WifiCmd;
struct WifiCmdBuilder;

struct Ack;
struct AckBuilder;

struct Log;
struct LogBuilder;

struct ServoState;
struct ServoStateBuilder;

struct Status;
struct StatusBuilder;

struct EncoderInfo;
struct EncoderInfoBuilder;

struct EncoderHealth;
struct EncoderHealthBuilder;

struct PulseResult;
struct PulseResultBuilder;

struct WalkEvent;
struct WalkEventBuilder;

struct WifiStatus;
struct WifiStatusBuilder;

struct Packet;
struct PacketBuilder;

enum class Channel : int8_t {
  BOTH = 0,
  ONE = 1,
  TWO = 2,
  MIN = BOTH,
  MAX = TWO
};

inline const Channel (&EnumValuesChannel())[3] {
  static const Channel values[] = {
    Channel::BOTH,
    Channel::ONE,
    Channel::TWO
  };
  return values;
}

inline const char * const *EnumNamesChannel() {
  static const char * const names[4] = {
    "BOTH",
    "ONE",
    "TWO",
    nullptr
  };
  return names;
}

inline const char *EnumNameChannel(Channel e) {
  if (::flatbuffers::IsOutRange(e, Channel::BOTH, Channel::TWO)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesChannel()[index];
}

enum class NumCmd : int8_t {
  GOTO = 0,
  MOVE_BY = 1,
  MAX_SPEED = 2,
  MAX_PWM = 3,
  MIN_PWM = 4,
  KP = 5,
  KI = 6,
  KD = 7,
  SET_DIR = 8,
  GROUND_SPEED = 9,
  AIR_SPEED = 10,
  MIN = GOTO,
  MAX = AIR_SPEED
};

inline const NumCmd (&EnumValuesNumCmd())[11] {
  static const NumCmd values[] = {
    NumCmd::GOTO,
    NumCmd::MOVE_BY,
    NumCmd::MAX_SPEED,
    NumCmd::MAX_PWM,
    NumCmd::MIN_PWM,
    NumCmd::KP,
    NumCmd::KI,
    NumCmd::KD,
    NumCmd::SET_DIR,
    NumCmd::GROUND_SPEED,
    NumCmd::AIR_SPEED
  };
  return values;
}

inline const char * const *EnumNamesNumCmd() {
  static const char * const names[12] = {
    "GOTO",
    "MOVE_BY",
    "MAX_SPEED",
    "MAX_PWM",
    "MIN_PWM",
    "KP",
    "KI",
    "KD",
    "SET_DIR",
    "GROUND_SPEED",
    "AIR_SPEED",
    nullptr
  };
  return names;
}

inline const char *EnumNameNumCmd(NumCmd e) {
  if (::flatbuffers::IsOutRange(e, NumCmd::GOTO, NumCmd::AIR_SPEED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNumCmd()[index];
}

enum class SimpleCmd : int8_t {
  STAND = 0,
  ZERO = 1,
  STOP = 2,
  ENC_HEALTH = 3,
  STATUS = 4,
  RESET = 5,
  HELP = 6,
  MIN = STAND,
  MAX = HELP
};

inline const SimpleCmd (&EnumValuesSimpleCmd())[7] {
  static const SimpleCmd values[] = {
    SimpleCmd::STAND,
    SimpleCmd::ZERO,
    SimpleCmd::STOP,
    SimpleCmd::ENC_HEALTH,
    SimpleCmd::STATUS,
    SimpleCmd::RESET,
    SimpleCmd::HELP
  };
  return values;
}

inline const char * const *EnumNamesSimpleCmd() {
  static const char * const names[8] = {
    "STAND",
    "ZERO",
    "STOP",
    "ENC_HEALTH",
    "STATUS",
    "RESET",
    "HELP",
    nullptr
  };
  return names;
}

inline const char *EnumNameSimpleCmd(SimpleCmd e) {
  if (::flatbuffers::IsOutRange(e, SimpleCmd::STAND, SimpleCmd::HELP)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSimpleCmd()[index];
}

enum class Toggle : int8_t {
  STATUS_STREAM = 0,
  RAW_STREAM = 1,
  MIN = STATUS_STREAM,
  MAX = RAW_STREAM
};

inline const Toggle (&EnumValuesToggle())[2] {
  static const Toggle values[] = {
    Toggle::STATUS_STREAM,
    Toggle::RAW_STREAM
  };
  return values;
}

inline const char * const *EnumNamesToggle() {
  static const char * const names[3] = {
    "STATUS_STREAM",
    "RAW_STREAM",
    nullptr
  };
  return names;
}

inline const char *EnumNameToggle(Toggle e) {
  if (::flatbuffers::IsOutRange(e, Toggle::STATUS_STREAM, Toggle::RAW_STREAM)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesToggle()[index];
}

enum class LogLevel : int8_t {
  INFO = 0,
  WARN = 1,
  ERROR = 2,
  MIN = INFO,
  MAX = ERROR
};

inline const LogLevel (&EnumValuesLogLevel())[3] {
  static const LogLevel values[] = {
    LogLevel::INFO,
    LogLevel::WARN,
    LogLevel::ERROR
  };
  return values;
}

inline const char * const *EnumNamesLogLevel() {
  static const char * const names[4] = {
    "INFO",
    "WARN",
    "ERROR",
    nullptr
  };
  return names;
}

inline const char *EnumNameLogLevel(LogLevel e) {
  if (::flatbuffers::IsOutRange(e, LogLevel::INFO, LogLevel::ERROR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLogLevel()[index];
}

enum class WifiState : int8_t {
  UNCONFIGURED = 0,
  CONNECTING = 1,
  CONNECTED = 2,
  FAILED = 3,
  MIN = UNCONFIGURED,
  MAX = FAILED
};

inline const WifiState (&EnumValuesWifiState())[4] {
  static const WifiState values[] = {
    WifiState::UNCONFIGURED,
    WifiState::CONNECTING,
    WifiState::CONNECTED,
    WifiState::FAILED
  };
  return values;
}

inline const char * const *EnumNamesWifiState() {
  static const char * const names[5] = {
    "UNCONFIGURED",
    "CONNECTING",
    "CONNECTED",
    "FAILED",
    nullptr
  };
  return names;
}

inline const char *EnumNameWifiState(WifiState e) {
  if (::flatbuffers::IsOutRange(e, WifiState::UNCONFIGURED, WifiState::FAILED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWifiState()[index];
}

enum class WalkPhase : int8_t {
  START = 0,
  LEADIN = 1,
  STEPPING = 2,
  LEADOUT = 3,
  DONE = 4,
  ABORTED = 5,
  MIN = START,
  MAX = ABORTED
};

inline const WalkPhase (&EnumValuesWalkPhase())[6] {
  static const WalkPhase values[] = {
    WalkPhase::START,
    WalkPhase::LEADIN,
    WalkPhase::STEPPING,
    WalkPhase::LEADOUT,
    WalkPhase::DONE,
    WalkPhase::ABORTED
  };
  return values;
}

inline const char * const *EnumNamesWalkPhase() {
  static const char * const names[7] = {
    "START",
    "LEADIN",
    "STEPPING",
    "LEADOUT",
    "DONE",
    "ABORTED",
    nullptr
  };
  return names;
}

inline const char *EnumNameWalkPhase(WalkPhase e) {
  if (::flatbuffers::IsOutRange(e, WalkPhase::START, WalkPhase::ABORTED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWalkPhase()[index];
}

enum class Msg : uint8_t {
  NONE = 0,
  NumberCmd = 1,
  SimpleAction = 2,
  Calibrate = 3,
  PulseCmd = 4,
  ToggleCmd = 5,
  WalkCmd = 6,
  WifiCmd = 7,
  Ack = 8,
  Log = 9,
  Status = 10,
  EncoderHealth = 11,
  PulseResult = 12,
  WalkEvent = 13,
  WifiStatus = 14,
  MIN = NONE,
  MAX = WifiStatus
};

inline const Msg (&EnumValuesMsg())[15] {
  static const Msg values[] = {
    Msg::NONE,
    Msg::NumberCmd,
    Msg::SimpleAction,
    Msg::Calibrate,
    Msg::PulseCmd,
    Msg::ToggleCmd,
    Msg::WalkCmd,
    Msg::WifiCmd,
    Msg::Ack,
    Msg::Log,
    Msg::Status,
    Msg::EncoderHealth,
    Msg::PulseResult,
    Msg::WalkEvent,
    Msg::WifiStatus
  };
  return values;
}

inline const char * const *EnumNamesMsg() {
  static const char * const names[16] = {
    "NONE",
    "NumberCmd",
    "SimpleAction",
    "Calibrate",
    "PulseCmd",
    "ToggleCmd",
    "WalkCmd",
    "WifiCmd",
    "Ack",
    "Log",
    "Status",
    "EncoderHealth",
    "PulseResult",
    "WalkEvent",
    "WifiStatus",
    nullptr
  };
  return names;
}

inline const char *EnumNameMsg(Msg e) {
  if (::flatbuffers::IsOutRange(e, Msg::NONE, Msg::WifiStatus)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMsg()[index];
}

template<typename T> struct MsgTraits {
  static const Msg enum_value = Msg::NONE;
};

template<> struct MsgTraits<pet::wire::NumberCmd> {
  static const Msg enum_value = Msg::NumberCmd;
};

template<> struct MsgTraits<pet::wire::SimpleAction> {
  static const Msg enum_value = Msg::SimpleAction;
};

template<> struct MsgTraits<pet::wire::Calibrate> {
  static const Msg enum_value = Msg::Calibrate;
};

template<> struct MsgTraits<pet::wire::PulseCmd> {
  static const Msg enum_value = Msg::PulseCmd;
};

template<> struct MsgTraits<pet::wire::ToggleCmd> {
  static const Msg enum_value = Msg::ToggleCmd;
};

template<> struct MsgTraits<pet::wire::WalkCmd> {
  static const Msg enum_value = Msg::WalkCmd;
};

template<> struct MsgTraits<pet::wire::WifiCmd> {
  static const Msg enum_value = Msg::WifiCmd;
};

template<> struct MsgTraits<pet::wire::Ack> {
  static const Msg enum_value = Msg::Ack;
};

template<> struct MsgTraits<pet::wire::Log> {
  static const Msg enum_value = Msg::Log;
};

template<> struct MsgTraits<pet::wire::Status> {
  static const Msg enum_value = Msg::Status;
};

template<> struct MsgTraits<pet::wire::EncoderHealth> {
  static const Msg enum_value = Msg::EncoderHealth;
};

template<> struct MsgTraits<pet::wire::PulseResult> {
  static const Msg enum_value = Msg::PulseResult;
};

template<> struct MsgTraits<pet::wire::WalkEvent> {
  static const Msg enum_value = Msg::WalkEvent;
};

template<> struct MsgTraits<pet::wire::WifiStatus> {
  static const Msg enum_value = Msg::WifiStatus;
};

template <bool B = false>
bool VerifyMsg(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Msg type);
template <bool B = false>
bool VerifyMsgVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Msg> *types);

struct NumberCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NumberCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CMD = 4,
    VT_CHANNEL = 6,
    VT_VALUE = 8
  };
  pet::wire::NumCmd cmd() const {
    return static_cast<pet::wire::NumCmd>(GetField<int8_t>(VT_CMD, 0));
  }
  pet::wire::Channel channel() const {
    return static_cast<pet::wire::Channel>(GetField<int8_t>(VT_CHANNEL, 0));
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CMD, 1) &&
           VerifyField<int8_t>(verifier, VT_CHANNEL, 1) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct NumberCmdBuilder {
  typedef NumberCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cmd(pet::wire::NumCmd cmd) {
    fbb_.AddElement<int8_t>(NumberCmd::VT_CMD, static_cast<int8_t>(cmd), 0);
  }
  void add_channel(pet::wire::Channel channel) {
    fbb_.AddElement<int8_t>(NumberCmd::VT_CHANNEL, static_cast<int8_t>(channel), 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(NumberCmd::VT_VALUE, value, 0.0f);
  }
  explicit NumberCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NumberCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NumberCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NumberCmd> CreateNumberCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::NumCmd cmd = pet::wire::NumCmd::GOTO,
    pet::wire::Channel channel = pet::wire::Channel::BOTH,
    float value = 0.0f) {
  NumberCmdBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_channel(channel);
  builder_.add_cmd(cmd);
  return builder_.Finish();
}

struct SimpleAction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SimpleActionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CMD = 4
  };
  pet::wire::SimpleCmd cmd() const {
    return static_cast<pet::wire::SimpleCmd>(GetField<int8_t>(VT_CMD, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CMD, 1) &&
           verifier.EndTable();
  }
};

struct SimpleActionBuilder {
  typedef SimpleAction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cmd(pet::wire::SimpleCmd cmd) {
    fbb_.AddElement<int8_t>(SimpleAction::VT_CMD, static_cast<int8_t>(cmd), 0);
  }
  explicit SimpleActionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SimpleAction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SimpleAction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SimpleAction> CreateSimpleAction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::SimpleCmd cmd = pet::wire::SimpleCmd::STAND) {
  SimpleActionBuilder builder_(_fbb);
  builder_.add_cmd(cmd);
  return builder_.Finish();
}

struct Calibrate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CalibrateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHANNEL = 4
  };
  pet::wire::Channel channel() const {
    return static_cast<pet::wire::Channel>(GetField<int8_t>(VT_CHANNEL, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CHANNEL, 1) &&
           verifier.EndTable();
  }
};

struct CalibrateBuilder {
  typedef Calibrate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_channel(pet::wire::Channel channel) {
    fbb_.AddElement<int8_t>(Calibrate::VT_CHANNEL, static_cast<int8_t>(channel), 0);
  }
  explicit CalibrateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Calibrate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Calibrate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Calibrate> CreateCalibrate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::Channel channel = pet::wire::Channel::BOTH) {
  CalibrateBuilder builder_(_fbb);
  builder_.add_channel(channel);
  return builder_.Finish();
}

struct PulseCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PulseCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHANNEL = 4,
    VT_PWM = 6,
    VT_MS = 8
  };
  pet::wire::Channel channel() const {
    return static_cast<pet::wire::Channel>(GetField<int8_t>(VT_CHANNEL, 0));
  }
  int16_t pwm() const {
    return GetField<int16_t>(VT_PWM, 0);
  }
  int16_t ms() const {
    return GetField<int16_t>(VT_MS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CHANNEL, 1) &&
           VerifyField<int16_t>(verifier, VT_PWM, 2) &&
           VerifyField<int16_t>(verifier, VT_MS, 2) &&
           verifier.EndTable();
  }
};

struct PulseCmdBuilder {
  typedef PulseCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_channel(pet::wire::Channel channel) {
    fbb_.AddElement<int8_t>(PulseCmd::VT_CHANNEL, static_cast<int8_t>(channel), 0);
  }
  void add_pwm(int16_t pwm) {
    fbb_.AddElement<int16_t>(PulseCmd::VT_PWM, pwm, 0);
  }
  void add_ms(int16_t ms) {
    fbb_.AddElement<int16_t>(PulseCmd::VT_MS, ms, 0);
  }
  explicit PulseCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PulseCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PulseCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PulseCmd> CreatePulseCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::Channel channel = pet::wire::Channel::BOTH,
    int16_t pwm = 0,
    int16_t ms = 0) {
  PulseCmdBuilder builder_(_fbb);
  builder_.add_ms(ms);
  builder_.add_pwm(pwm);
  builder_.add_channel(channel);
  return builder_.Finish();
}

struct ToggleCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ToggleCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WHICH = 4
  };
  pet::wire::Toggle which() const {
    return static_cast<pet::wire::Toggle>(GetField<int8_t>(VT_WHICH, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_WHICH, 1) &&
           verifier.EndTable();
  }
};

struct ToggleCmdBuilder {
  typedef ToggleCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_which(pet::wire::Toggle which) {
    fbb_.AddElement<int8_t>(ToggleCmd::VT_WHICH, static_cast<int8_t>(which), 0);
  }
  explicit ToggleCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ToggleCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ToggleCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ToggleCmd> CreateToggleCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::Toggle which = pet::wire::Toggle::STATUS_STREAM) {
  ToggleCmdBuilder builder_(_fbb);
  builder_.add_which(which);
  return builder_.Finish();
}

struct WalkCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WalkCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STEPS = 4,
    VT_PHASE_DEG = 6
  };
  int32_t steps() const {
    return GetField<int32_t>(VT_STEPS, 0);
  }
  float phase_deg() const {
    return GetField<float>(VT_PHASE_DEG, 180.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_STEPS, 4) &&
           VerifyField<float>(verifier, VT_PHASE_DEG, 4) &&
           verifier.EndTable();
  }
};

struct WalkCmdBuilder {
  typedef WalkCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_steps(int32_t steps) {
    fbb_.AddElement<int32_t>(WalkCmd::VT_STEPS, steps, 0);
  }
  void add_phase_deg(float phase_deg) {
    fbb_.AddElement<float>(WalkCmd::VT_PHASE_DEG, phase_deg, 180.0f);
  }
  explicit WalkCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WalkCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WalkCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WalkCmd> CreateWalkCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t steps = 0,
    float phase_deg = 180.0f) {
  WalkCmdBuilder builder_(_fbb);
  builder_.add_phase_deg(phase_deg);
  builder_.add_steps(steps);
  return builder_.Finish();
}

struct WifiCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WifiCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SSID = 4,
    VT_PASSWORD = 6
  };
  const ::flatbuffers::String *ssid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SSID);
  }
  const ::flatbuffers::String *password() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PASSWORD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SSID) &&
           verifier.VerifyString(ssid()) &&
           VerifyOffset(verifier, VT_PASSWORD) &&
           verifier.VerifyString(password()) &&
           verifier.EndTable();
  }
};

struct WifiCmdBuilder {
  typedef WifiCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ssid(::flatbuffers::Offset<::flatbuffers::String> ssid) {
    fbb_.AddOffset(WifiCmd::VT_SSID, ssid);
  }
  void add_password(::flatbuffers::Offset<::flatbuffers::String> password) {
    fbb_.AddOffset(WifiCmd::VT_PASSWORD, password);
  }
  explicit WifiCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WifiCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WifiCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WifiCmd> CreateWifiCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> ssid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> password = 0) {
  WifiCmdBuilder builder_(_fbb);
  builder_.add_password(password);
  builder_.add_ssid(ssid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WifiCmd> CreateWifiCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *ssid = nullptr,
    const char *password = nullptr) {
  auto ssid__ = ssid ? _fbb.CreateString(ssid) : 0;
  auto password__ = password ? _fbb.CreateString(password) : 0;
  return pet::wire::CreateWifiCmd(
      _fbb,
      ssid__,
      password__);
}

struct Ack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AckBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OK = 4,
    VT_DETAIL = 6
  };
  bool ok() const {
    return GetField<uint8_t>(VT_OK, 1) != 0;
  }
  const ::flatbuffers::String *detail() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DETAIL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_OK, 1) &&
           VerifyOffset(verifier, VT_DETAIL) &&
           verifier.VerifyString(detail()) &&
           verifier.EndTable();
  }
};

struct AckBuilder {
  typedef Ack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ok(bool ok) {
    fbb_.AddElement<uint8_t>(Ack::VT_OK, static_cast<uint8_t>(ok), 1);
  }
  void add_detail(::flatbuffers::Offset<::flatbuffers::String> detail) {
    fbb_.AddOffset(Ack::VT_DETAIL, detail);
  }
  explicit AckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Ack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Ack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Ack> CreateAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool ok = true,
    ::flatbuffers::Offset<::flatbuffers::String> detail = 0) {
  AckBuilder builder_(_fbb);
  builder_.add_detail(detail);
  builder_.add_ok(ok);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Ack> CreateAckDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool ok = true,
    const char *detail = nullptr) {
  auto detail__ = detail ? _fbb.CreateString(detail) : 0;
  return pet::wire::CreateAck(
      _fbb,
      ok,
      detail__);
}

struct Log FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LogBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEVEL = 4,
    VT_TEXT = 6
  };
  pet::wire::LogLevel level() const {
    return static_cast<pet::wire::LogLevel>(GetField<int8_t>(VT_LEVEL, 0));
  }
  const ::flatbuffers::String *text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_LEVEL, 1) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           verifier.EndTable();
  }
};

struct LogBuilder {
  typedef Log Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_level(pet::wire::LogLevel level) {
    fbb_.AddElement<int8_t>(Log::VT_LEVEL, static_cast<int8_t>(level), 0);
  }
  void add_text(::flatbuffers::Offset<::flatbuffers::String> text) {
    fbb_.AddOffset(Log::VT_TEXT, text);
  }
  explicit LogBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Log> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Log>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Log> CreateLog(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::LogLevel level = pet::wire::LogLevel::INFO,
    ::flatbuffers::Offset<::flatbuffers::String> text = 0) {
  LogBuilder builder_(_fbb);
  builder_.add_text(text);
  builder_.add_level(level);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Log> CreateLogDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::LogLevel level = pet::wire::LogLevel::INFO,
    const char *text = nullptr) {
  auto text__ = text ? _fbb.CreateString(text) : 0;
  return pet::wire::CreateLog(
      _fbb,
      level,
      text__);
}

struct ServoState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServoStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHANNEL = 4,
    VT_ENABLED = 6,
    VT_FAULT = 8,
    VT_FAULT_NAME = 10,
    VT_POSITION_TURNS = 12,
    VT_TARGET_TURNS = 14,
    VT_VELOCITY_TPS = 16,
    VT_PWM = 18
  };
  pet::wire::Channel channel() const {
    return static_cast<pet::wire::Channel>(GetField<int8_t>(VT_CHANNEL, 0));
  }
  bool enabled() const {
    return GetField<uint8_t>(VT_ENABLED, 0) != 0;
  }
  bool fault() const {
    return GetField<uint8_t>(VT_FAULT, 0) != 0;
  }
  const ::flatbuffers::String *fault_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FAULT_NAME);
  }
  float position_turns() const {
    return GetField<float>(VT_POSITION_TURNS, 0.0f);
  }
  float target_turns() const {
    return GetField<float>(VT_TARGET_TURNS, 0.0f);
  }
  float velocity_tps() const {
    return GetField<float>(VT_VELOCITY_TPS, 0.0f);
  }
  int16_t pwm() const {
    return GetField<int16_t>(VT_PWM, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CHANNEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_ENABLED, 1) &&
           VerifyField<uint8_t>(verifier, VT_FAULT, 1) &&
           VerifyOffset(verifier, VT_FAULT_NAME) &&
           verifier.VerifyString(fault_name()) &&
           VerifyField<float>(verifier, VT_POSITION_TURNS, 4) &&
           VerifyField<float>(verifier, VT_TARGET_TURNS, 4) &&
           VerifyField<float>(verifier, VT_VELOCITY_TPS, 4) &&
           VerifyField<int16_t>(verifier, VT_PWM, 2) &&
           verifier.EndTable();
  }
};

struct ServoStateBuilder {
  typedef ServoState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_channel(pet::wire::Channel channel) {
    fbb_.AddElement<int8_t>(ServoState::VT_CHANNEL, static_cast<int8_t>(channel), 0);
  }
  void add_enabled(bool enabled) {
    fbb_.AddElement<uint8_t>(ServoState::VT_ENABLED, static_cast<uint8_t>(enabled), 0);
  }
  void add_fault(bool fault) {
    fbb_.AddElement<uint8_t>(ServoState::VT_FAULT, static_cast<uint8_t>(fault), 0);
  }
  void add_fault_name(::flatbuffers::Offset<::flatbuffers::String> fault_name) {
    fbb_.AddOffset(ServoState::VT_FAULT_NAME, fault_name);
  }
  void add_position_turns(float position_turns) {
    fbb_.AddElement<float>(ServoState::VT_POSITION_TURNS, position_turns, 0.0f);
  }
  void add_target_turns(float target_turns) {
    fbb_.AddElement<float>(ServoState::VT_TARGET_TURNS, target_turns, 0.0f);
  }
  void add_velocity_tps(float velocity_tps) {
    fbb_.AddElement<float>(ServoState::VT_VELOCITY_TPS, velocity_tps, 0.0f);
  }
  void add_pwm(int16_t pwm) {
    fbb_.AddElement<int16_t>(ServoState::VT_PWM, pwm, 0);
  }
  explicit ServoStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServoState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServoState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServoState> CreateServoState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::Channel channel = pet::wire::Channel::BOTH,
    bool enabled = false,
    bool fault = false,
    ::flatbuffers::Offset<::flatbuffers::String> fault_name = 0,
    float position_turns = 0.0f,
    float target_turns = 0.0f,
    float velocity_tps = 0.0f,
    int16_t pwm = 0) {
  ServoStateBuilder builder_(_fbb);
  builder_.add_velocity_tps(velocity_tps);
  builder_.add_target_turns(target_turns);
  builder_.add_position_turns(position_turns);
  builder_.add_fault_name(fault_name);
  builder_.add_pwm(pwm);
  builder_.add_fault(fault);
  builder_.add_enabled(enabled);
  builder_.add_channel(channel);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServoState> CreateServoStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::Channel channel = pet::wire::Channel::BOTH,
    bool enabled = false,
    bool fault = false,
    const char *fault_name = nullptr,
    float position_turns = 0.0f,
    float target_turns = 0.0f,
    float velocity_tps = 0.0f,
    int16_t pwm = 0) {
  auto fault_name__ = fault_name ? _fbb.CreateString(fault_name) : 0;
  return pet::wire::CreateServoState(
      _fbb,
      channel,
      enabled,
      fault,
      fault_name__,
      position_turns,
      target_turns,
      velocity_tps,
      pwm);
}

struct Status FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StatusBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVOS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<pet::wire::ServoState>> *servos() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<pet::wire::ServoState>> *>(VT_SERVOS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SERVOS) &&
           verifier.VerifyVector(servos()) &&
           verifier.VerifyVectorOfTables(servos()) &&
           verifier.EndTable();
  }
};

struct StatusBuilder {
  typedef Status Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_servos(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<pet::wire::ServoState>>> servos) {
    fbb_.AddOffset(Status::VT_SERVOS, servos);
  }
  explicit StatusBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Status> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Status>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Status> CreateStatus(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<pet::wire::ServoState>>> servos = 0) {
  StatusBuilder builder_(_fbb);
  builder_.add_servos(servos);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Status> CreateStatusDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<pet::wire::ServoState>> *servos = nullptr) {
  auto servos__ = servos ? _fbb.CreateVector<::flatbuffers::Offset<pet::wire::ServoState>>(*servos) : 0;
  return pet::wire::CreateStatus(
      _fbb,
      servos__);
}

struct EncoderInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EncoderInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHANNEL = 4,
    VT_CONNECTED = 6,
    VT_MAGNET_DETECTED = 8,
    VT_MAGNET_TOO_WEAK = 10,
    VT_MAGNET_TOO_STRONG = 12,
    VT_AGC = 14,
    VT_MAGNITUDE = 16,
    VT_ANGLE_DEG = 18
  };
  pet::wire::Channel channel() const {
    return static_cast<pet::wire::Channel>(GetField<int8_t>(VT_CHANNEL, 0));
  }
  bool connected() const {
    return GetField<uint8_t>(VT_CONNECTED, 0) != 0;
  }
  bool magnet_detected() const {
    return GetField<uint8_t>(VT_MAGNET_DETECTED, 0) != 0;
  }
  bool magnet_too_weak() const {
    return GetField<uint8_t>(VT_MAGNET_TOO_WEAK, 0) != 0;
  }
  bool magnet_too_strong() const {
    return GetField<uint8_t>(VT_MAGNET_TOO_STRONG, 0) != 0;
  }
  uint8_t agc() const {
    return GetField<uint8_t>(VT_AGC, 0);
  }
  uint16_t magnitude() const {
    return GetField<uint16_t>(VT_MAGNITUDE, 0);
  }
  float angle_deg() const {
    return GetField<float>(VT_ANGLE_DEG, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CHANNEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_CONNECTED, 1) &&
           VerifyField<uint8_t>(verifier, VT_MAGNET_DETECTED, 1) &&
           VerifyField<uint8_t>(verifier, VT_MAGNET_TOO_WEAK, 1) &&
           VerifyField<uint8_t>(verifier, VT_MAGNET_TOO_STRONG, 1) &&
           VerifyField<uint8_t>(verifier, VT_AGC, 1) &&
           VerifyField<uint16_t>(verifier, VT_MAGNITUDE, 2) &&
           VerifyField<float>(verifier, VT_ANGLE_DEG, 4) &&
           verifier.EndTable();
  }
};

struct EncoderInfoBuilder {
  typedef EncoderInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_channel(pet::wire::Channel channel) {
    fbb_.AddElement<int8_t>(EncoderInfo::VT_CHANNEL, static_cast<int8_t>(channel), 0);
  }
  void add_connected(bool connected) {
    fbb_.AddElement<uint8_t>(EncoderInfo::VT_CONNECTED, static_cast<uint8_t>(connected), 0);
  }
  void add_magnet_detected(bool magnet_detected) {
    fbb_.AddElement<uint8_t>(EncoderInfo::VT_MAGNET_DETECTED, static_cast<uint8_t>(magnet_detected), 0);
  }
  void add_magnet_too_weak(bool magnet_too_weak) {
    fbb_.AddElement<uint8_t>(EncoderInfo::VT_MAGNET_TOO_WEAK, static_cast<uint8_t>(magnet_too_weak), 0);
  }
  void add_magnet_too_strong(bool magnet_too_strong) {
    fbb_.AddElement<uint8_t>(EncoderInfo::VT_MAGNET_TOO_STRONG, static_cast<uint8_t>(magnet_too_strong), 0);
  }
  void add_agc(uint8_t agc) {
    fbb_.AddElement<uint8_t>(EncoderInfo::VT_AGC, agc, 0);
  }
  void add_magnitude(uint16_t magnitude) {
    fbb_.AddElement<uint16_t>(EncoderInfo::VT_MAGNITUDE, magnitude, 0);
  }
  void add_angle_deg(float angle_deg) {
    fbb_.AddElement<float>(EncoderInfo::VT_ANGLE_DEG, angle_deg, 0.0f);
  }
  explicit EncoderInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EncoderInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EncoderInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EncoderInfo> CreateEncoderInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::Channel channel = pet::wire::Channel::BOTH,
    bool connected = false,
    bool magnet_detected = false,
    bool magnet_too_weak = false,
    bool magnet_too_strong = false,
    uint8_t agc = 0,
    uint16_t magnitude = 0,
    float angle_deg = 0.0f) {
  EncoderInfoBuilder builder_(_fbb);
  builder_.add_angle_deg(angle_deg);
  builder_.add_magnitude(magnitude);
  builder_.add_agc(agc);
  builder_.add_magnet_too_strong(magnet_too_strong);
  builder_.add_magnet_too_weak(magnet_too_weak);
  builder_.add_magnet_detected(magnet_detected);
  builder_.add_connected(connected);
  builder_.add_channel(channel);
  return builder_.Finish();
}

struct EncoderHealth FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EncoderHealthBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENCODERS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<pet::wire::EncoderInfo>> *encoders() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<pet::wire::EncoderInfo>> *>(VT_ENCODERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENCODERS) &&
           verifier.VerifyVector(encoders()) &&
           verifier.VerifyVectorOfTables(encoders()) &&
           verifier.EndTable();
  }
};

struct EncoderHealthBuilder {
  typedef EncoderHealth Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_encoders(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<pet::wire::EncoderInfo>>> encoders) {
    fbb_.AddOffset(EncoderHealth::VT_ENCODERS, encoders);
  }
  explicit EncoderHealthBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EncoderHealth> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EncoderHealth>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EncoderHealth> CreateEncoderHealth(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<pet::wire::EncoderInfo>>> encoders = 0) {
  EncoderHealthBuilder builder_(_fbb);
  builder_.add_encoders(encoders);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EncoderHealth> CreateEncoderHealthDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<pet::wire::EncoderInfo>> *encoders = nullptr) {
  auto encoders__ = encoders ? _fbb.CreateVector<::flatbuffers::Offset<pet::wire::EncoderInfo>>(*encoders) : 0;
  return pet::wire::CreateEncoderHealth(
      _fbb,
      encoders__);
}

struct PulseResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PulseResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHANNEL = 4,
    VT_PWM = 6,
    VT_MS = 8,
    VT_ENC1_DELTA_COUNTS = 10,
    VT_ENC1_DELTA_TURNS = 12,
    VT_ENC2_DELTA_COUNTS = 14,
    VT_ENC2_DELTA_TURNS = 16,
    VT_CROSS_WIRED = 18
  };
  pet::wire::Channel channel() const {
    return static_cast<pet::wire::Channel>(GetField<int8_t>(VT_CHANNEL, 0));
  }
  int16_t pwm() const {
    return GetField<int16_t>(VT_PWM, 0);
  }
  int16_t ms() const {
    return GetField<int16_t>(VT_MS, 0);
  }
  int64_t enc1_delta_counts() const {
    return GetField<int64_t>(VT_ENC1_DELTA_COUNTS, 0);
  }
  float enc1_delta_turns() const {
    return GetField<float>(VT_ENC1_DELTA_TURNS, 0.0f);
  }
  int64_t enc2_delta_counts() const {
    return GetField<int64_t>(VT_ENC2_DELTA_COUNTS, 0);
  }
  float enc2_delta_turns() const {
    return GetField<float>(VT_ENC2_DELTA_TURNS, 0.0f);
  }
  bool cross_wired() const {
    return GetField<uint8_t>(VT_CROSS_WIRED, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CHANNEL, 1) &&
           VerifyField<int16_t>(verifier, VT_PWM, 2) &&
           VerifyField<int16_t>(verifier, VT_MS, 2) &&
           VerifyField<int64_t>(verifier, VT_ENC1_DELTA_COUNTS, 8) &&
           VerifyField<float>(verifier, VT_ENC1_DELTA_TURNS, 4) &&
           VerifyField<int64_t>(verifier, VT_ENC2_DELTA_COUNTS, 8) &&
           VerifyField<float>(verifier, VT_ENC2_DELTA_TURNS, 4) &&
           VerifyField<uint8_t>(verifier, VT_CROSS_WIRED, 1) &&
           verifier.EndTable();
  }
};

struct PulseResultBuilder {
  typedef PulseResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_channel(pet::wire::Channel channel) {
    fbb_.AddElement<int8_t>(PulseResult::VT_CHANNEL, static_cast<int8_t>(channel), 0);
  }
  void add_pwm(int16_t pwm) {
    fbb_.AddElement<int16_t>(PulseResult::VT_PWM, pwm, 0);
  }
  void add_ms(int16_t ms) {
    fbb_.AddElement<int16_t>(PulseResult::VT_MS, ms, 0);
  }
  void add_enc1_delta_counts(int64_t enc1_delta_counts) {
    fbb_.AddElement<int64_t>(PulseResult::VT_ENC1_DELTA_COUNTS, enc1_delta_counts, 0);
  }
  void add_enc1_delta_turns(float enc1_delta_turns) {
    fbb_.AddElement<float>(PulseResult::VT_ENC1_DELTA_TURNS, enc1_delta_turns, 0.0f);
  }
  void add_enc2_delta_counts(int64_t enc2_delta_counts) {
    fbb_.AddElement<int64_t>(PulseResult::VT_ENC2_DELTA_COUNTS, enc2_delta_counts, 0);
  }
  void add_enc2_delta_turns(float enc2_delta_turns) {
    fbb_.AddElement<float>(PulseResult::VT_ENC2_DELTA_TURNS, enc2_delta_turns, 0.0f);
  }
  void add_cross_wired(bool cross_wired) {
    fbb_.AddElement<uint8_t>(PulseResult::VT_CROSS_WIRED, static_cast<uint8_t>(cross_wired), 0);
  }
  explicit PulseResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PulseResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PulseResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PulseResult> CreatePulseResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::Channel channel = pet::wire::Channel::BOTH,
    int16_t pwm = 0,
    int16_t ms = 0,
    int64_t enc1_delta_counts = 0,
    float enc1_delta_turns = 0.0f,
    int64_t enc2_delta_counts = 0,
    float enc2_delta_turns = 0.0f,
    bool cross_wired = false) {
  PulseResultBuilder builder_(_fbb);
  builder_.add_enc2_delta_counts(enc2_delta_counts);
  builder_.add_enc1_delta_counts(enc1_delta_counts);
  builder_.add_enc2_delta_turns(enc2_delta_turns);
  builder_.add_enc1_delta_turns(enc1_delta_turns);
  builder_.add_ms(ms);
  builder_.add_pwm(pwm);
  builder_.add_cross_wired(cross_wired);
  builder_.add_channel(channel);
  return builder_.Finish();
}

struct WalkEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WalkEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PHASE = 4,
    VT_STEPS = 6,
    VT_LEAD_SERVO = 8
  };
  pet::wire::WalkPhase phase() const {
    return static_cast<pet::wire::WalkPhase>(GetField<int8_t>(VT_PHASE, 0));
  }
  int32_t steps() const {
    return GetField<int32_t>(VT_STEPS, 0);
  }
  int8_t lead_servo() const {
    return GetField<int8_t>(VT_LEAD_SERVO, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_PHASE, 1) &&
           VerifyField<int32_t>(verifier, VT_STEPS, 4) &&
           VerifyField<int8_t>(verifier, VT_LEAD_SERVO, 1) &&
           verifier.EndTable();
  }
};

struct WalkEventBuilder {
  typedef WalkEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_phase(pet::wire::WalkPhase phase) {
    fbb_.AddElement<int8_t>(WalkEvent::VT_PHASE, static_cast<int8_t>(phase), 0);
  }
  void add_steps(int32_t steps) {
    fbb_.AddElement<int32_t>(WalkEvent::VT_STEPS, steps, 0);
  }
  void add_lead_servo(int8_t lead_servo) {
    fbb_.AddElement<int8_t>(WalkEvent::VT_LEAD_SERVO, lead_servo, 0);
  }
  explicit WalkEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WalkEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WalkEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WalkEvent> CreateWalkEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::WalkPhase phase = pet::wire::WalkPhase::START,
    int32_t steps = 0,
    int8_t lead_servo = 0) {
  WalkEventBuilder builder_(_fbb);
  builder_.add_steps(steps);
  builder_.add_lead_servo(lead_servo);
  builder_.add_phase(phase);
  return builder_.Finish();
}

struct WifiStatus FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WifiStatusBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATE = 4,
    VT_SSID = 6,
    VT_IP = 8,
    VT_HOSTNAME = 10,
    VT_RSSI = 12,
    VT_WS_CLIENTS = 14
  };
  pet::wire::WifiState state() const {
    return static_cast<pet::wire::WifiState>(GetField<int8_t>(VT_STATE, 0));
  }
  const ::flatbuffers::String *ssid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SSID);
  }
  const ::flatbuffers::String *ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IP);
  }
  const ::flatbuffers::String *hostname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_HOSTNAME);
  }
  int16_t rssi() const {
    return GetField<int16_t>(VT_RSSI, 0);
  }
  uint8_t ws_clients() const {
    return GetField<uint8_t>(VT_WS_CLIENTS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STATE, 1) &&
           VerifyOffset(verifier, VT_SSID) &&
           verifier.VerifyString(ssid()) &&
           VerifyOffset(verifier, VT_IP) &&
           verifier.VerifyString(ip()) &&
           VerifyOffset(verifier, VT_HOSTNAME) &&
           verifier.VerifyString(hostname()) &&
           VerifyField<int16_t>(verifier, VT_RSSI, 2) &&
           VerifyField<uint8_t>(verifier, VT_WS_CLIENTS, 1) &&
           verifier.EndTable();
  }
};

struct WifiStatusBuilder {
  typedef WifiStatus Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_state(pet::wire::WifiState state) {
    fbb_.AddElement<int8_t>(WifiStatus::VT_STATE, static_cast<int8_t>(state), 0);
  }
  void add_ssid(::flatbuffers::Offset<::flatbuffers::String> ssid) {
    fbb_.AddOffset(WifiStatus::VT_SSID, ssid);
  }
  void add_ip(::flatbuffers::Offset<::flatbuffers::String> ip) {
    fbb_.AddOffset(WifiStatus::VT_IP, ip);
  }
  void add_hostname(::flatbuffers::Offset<::flatbuffers::String> hostname) {
    fbb_.AddOffset(WifiStatus::VT_HOSTNAME, hostname);
  }
  void add_rssi(int16_t rssi) {
    fbb_.AddElement<int16_t>(WifiStatus::VT_RSSI, rssi, 0);
  }
  void add_ws_clients(uint8_t ws_clients) {
    fbb_.AddElement<uint8_t>(WifiStatus::VT_WS_CLIENTS, ws_clients, 0);
  }
  explicit WifiStatusBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WifiStatus> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WifiStatus>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WifiStatus> CreateWifiStatus(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::WifiState state = pet::wire::WifiState::UNCONFIGURED,
    ::flatbuffers::Offset<::flatbuffers::String> ssid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ip = 0,
    ::flatbuffers::Offset<::flatbuffers::String> hostname = 0,
    int16_t rssi = 0,
    uint8_t ws_clients = 0) {
  WifiStatusBuilder builder_(_fbb);
  builder_.add_hostname(hostname);
  builder_.add_ip(ip);
  builder_.add_ssid(ssid);
  builder_.add_rssi(rssi);
  builder_.add_ws_clients(ws_clients);
  builder_.add_state(state);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WifiStatus> CreateWifiStatusDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    pet::wire::WifiState state = pet::wire::WifiState::UNCONFIGURED,
    const char *ssid = nullptr,
    const char *ip = nullptr,
    const char *hostname = nullptr,
    int16_t rssi = 0,
    uint8_t ws_clients = 0) {
  auto ssid__ = ssid ? _fbb.CreateString(ssid) : 0;
  auto ip__ = ip ? _fbb.CreateString(ip) : 0;
  auto hostname__ = hostname ? _fbb.CreateString(hostname) : 0;
  return pet::wire::CreateWifiStatus(
      _fbb,
      state,
      ssid__,
      ip__,
      hostname__,
      rssi,
      ws_clients);
}

struct Packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQ_ID = 4,
    VT_MSG_TYPE = 6,
    VT_MSG = 8
  };
  uint32_t req_id() const {
    return GetField<uint32_t>(VT_REQ_ID, 0);
  }
  pet::wire::Msg msg_type() const {
    return static_cast<pet::wire::Msg>(GetField<uint8_t>(VT_MSG_TYPE, 0));
  }
  const void *msg() const {
    return GetPointer<const void *>(VT_MSG);
  }
  template<typename T> const T *msg_as() const;
  const pet::wire::NumberCmd *msg_as_NumberCmd() const {
    return msg_type() == pet::wire::Msg::NumberCmd ? static_cast<const pet::wire::NumberCmd *>(msg()) : nullptr;
  }
  const pet::wire::SimpleAction *msg_as_SimpleAction() const {
    return msg_type() == pet::wire::Msg::SimpleAction ? static_cast<const pet::wire::SimpleAction *>(msg()) : nullptr;
  }
  const pet::wire::Calibrate *msg_as_Calibrate() const {
    return msg_type() == pet::wire::Msg::Calibrate ? static_cast<const pet::wire::Calibrate *>(msg()) : nullptr;
  }
  const pet::wire::PulseCmd *msg_as_PulseCmd() const {
    return msg_type() == pet::wire::Msg::PulseCmd ? static_cast<const pet::wire::PulseCmd *>(msg()) : nullptr;
  }
  const pet::wire::ToggleCmd *msg_as_ToggleCmd() const {
    return msg_type() == pet::wire::Msg::ToggleCmd ? static_cast<const pet::wire::ToggleCmd *>(msg()) : nullptr;
  }
  const pet::wire::WalkCmd *msg_as_WalkCmd() const {
    return msg_type() == pet::wire::Msg::WalkCmd ? static_cast<const pet::wire::WalkCmd *>(msg()) : nullptr;
  }
  const pet::wire::WifiCmd *msg_as_WifiCmd() const {
    return msg_type() == pet::wire::Msg::WifiCmd ? static_cast<const pet::wire::WifiCmd *>(msg()) : nullptr;
  }
  const pet::wire::Ack *msg_as_Ack() const {
    return msg_type() == pet::wire::Msg::Ack ? static_cast<const pet::wire::Ack *>(msg()) : nullptr;
  }
  const pet::wire::Log *msg_as_Log() const {
    return msg_type() == pet::wire::Msg::Log ? static_cast<const pet::wire::Log *>(msg()) : nullptr;
  }
  const pet::wire::Status *msg_as_Status() const {
    return msg_type() == pet::wire::Msg::Status ? static_cast<const pet::wire::Status *>(msg()) : nullptr;
  }
  const pet::wire::EncoderHealth *msg_as_EncoderHealth() const {
    return msg_type() == pet::wire::Msg::EncoderHealth ? static_cast<const pet::wire::EncoderHealth *>(msg()) : nullptr;
  }
  const pet::wire::PulseResult *msg_as_PulseResult() const {
    return msg_type() == pet::wire::Msg::PulseResult ? static_cast<const pet::wire::PulseResult *>(msg()) : nullptr;
  }
  const pet::wire::WalkEvent *msg_as_WalkEvent() const {
    return msg_type() == pet::wire::Msg::WalkEvent ? static_cast<const pet::wire::WalkEvent *>(msg()) : nullptr;
  }
  const pet::wire::WifiStatus *msg_as_WifiStatus() const {
    return msg_type() == pet::wire::Msg::WifiStatus ? static_cast<const pet::wire::WifiStatus *>(msg()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQ_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_MSG_TYPE, 1) &&
           VerifyOffset(verifier, VT_MSG) &&
           VerifyMsg(verifier, msg(), msg_type()) &&
           verifier.EndTable();
  }
};

template<> inline const pet::wire::NumberCmd *Packet::msg_as<pet::wire::NumberCmd>() const {
  return msg_as_NumberCmd();
}

template<> inline const pet::wire::SimpleAction *Packet::msg_as<pet::wire::SimpleAction>() const {
  return msg_as_SimpleAction();
}

template<> inline const pet::wire::Calibrate *Packet::msg_as<pet::wire::Calibrate>() const {
  return msg_as_Calibrate();
}

template<> inline const pet::wire::PulseCmd *Packet::msg_as<pet::wire::PulseCmd>() const {
  return msg_as_PulseCmd();
}

template<> inline const pet::wire::ToggleCmd *Packet::msg_as<pet::wire::ToggleCmd>() const {
  return msg_as_ToggleCmd();
}

template<> inline const pet::wire::WalkCmd *Packet::msg_as<pet::wire::WalkCmd>() const {
  return msg_as_WalkCmd();
}

template<> inline const pet::wire::WifiCmd *Packet::msg_as<pet::wire::WifiCmd>() const {
  return msg_as_WifiCmd();
}

template<> inline const pet::wire::Ack *Packet::msg_as<pet::wire::Ack>() const {
  return msg_as_Ack();
}

template<> inline const pet::wire::Log *Packet::msg_as<pet::wire::Log>() const {
  return msg_as_Log();
}

template<> inline const pet::wire::Status *Packet::msg_as<pet::wire::Status>() const {
  return msg_as_Status();
}

template<> inline const pet::wire::EncoderHealth *Packet::msg_as<pet::wire::EncoderHealth>() const {
  return msg_as_EncoderHealth();
}

template<> inline const pet::wire::PulseResult *Packet::msg_as<pet::wire::PulseResult>() const {
  return msg_as_PulseResult();
}

template<> inline const pet::wire::WalkEvent *Packet::msg_as<pet::wire::WalkEvent>() const {
  return msg_as_WalkEvent();
}

template<> inline const pet::wire::WifiStatus *Packet::msg_as<pet::wire::WifiStatus>() const {
  return msg_as_WifiStatus();
}

struct PacketBuilder {
  typedef Packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_req_id(uint32_t req_id) {
    fbb_.AddElement<uint32_t>(Packet::VT_REQ_ID, req_id, 0);
  }
  void add_msg_type(pet::wire::Msg msg_type) {
    fbb_.AddElement<uint8_t>(Packet::VT_MSG_TYPE, static_cast<uint8_t>(msg_type), 0);
  }
  void add_msg(::flatbuffers::Offset<void> msg) {
    fbb_.AddOffset(Packet::VT_MSG, msg);
  }
  explicit PacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Packet> CreatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_id = 0,
    pet::wire::Msg msg_type = pet::wire::Msg::NONE,
    ::flatbuffers::Offset<void> msg = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_msg(msg);
  builder_.add_req_id(req_id);
  builder_.add_msg_type(msg_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyMsg(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Msg type) {
  switch (type) {
    case Msg::NONE: {
      return true;
    }
    case Msg::NumberCmd: {
      auto ptr = reinterpret_cast<const pet::wire::NumberCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::SimpleAction: {
      auto ptr = reinterpret_cast<const pet::wire::SimpleAction *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::Calibrate: {
      auto ptr = reinterpret_cast<const pet::wire::Calibrate *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::PulseCmd: {
      auto ptr = reinterpret_cast<const pet::wire::PulseCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::ToggleCmd: {
      auto ptr = reinterpret_cast<const pet::wire::ToggleCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::WalkCmd: {
      auto ptr = reinterpret_cast<const pet::wire::WalkCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::WifiCmd: {
      auto ptr = reinterpret_cast<const pet::wire::WifiCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::Ack: {
      auto ptr = reinterpret_cast<const pet::wire::Ack *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::Log: {
      auto ptr = reinterpret_cast<const pet::wire::Log *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::Status: {
      auto ptr = reinterpret_cast<const pet::wire::Status *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::EncoderHealth: {
      auto ptr = reinterpret_cast<const pet::wire::EncoderHealth *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::PulseResult: {
      auto ptr = reinterpret_cast<const pet::wire::PulseResult *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::WalkEvent: {
      auto ptr = reinterpret_cast<const pet::wire::WalkEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Msg::WifiStatus: {
      auto ptr = reinterpret_cast<const pet::wire::WifiStatus *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyMsgVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Msg> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMsg(
        verifier,  values->Get(i), types->GetEnum<Msg>(i))) {
      return false;
    }
  }
  return true;
}

inline const pet::wire::Packet *GetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<pet::wire::Packet>(buf);
}

inline const pet::wire::Packet *GetSizePrefixedPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<pet::wire::Packet>(buf);
}

inline const char *PacketIdentifier() {
  return "PET1";
}

inline bool PacketBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, PacketIdentifier());
}

inline bool SizePrefixedPacketBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, PacketIdentifier(), true);
}

template <bool B = false>
inline bool VerifyPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<pet::wire::Packet>(PacketIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<pet::wire::Packet>(PacketIdentifier());
}

inline void FinishPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<pet::wire::Packet> root) {
  fbb.Finish(root, PacketIdentifier());
}

inline void FinishSizePrefixedPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<pet::wire::Packet> root) {
  fbb.FinishSizePrefixed(root, PacketIdentifier());
}

}  // namespace wire
}  // namespace pet

#endif  // FLATBUFFERS_GENERATED_PET_PET_WIRE_H_
